### ISSUE TITLE
singularity container missing ANTs

### ISSUE THREAD

**Issue by pfuchs** [NYU-DiffusionMRI/DESIGNER-v2#21]
Singularity container metadata:
```
org.label-schema.build-arch: amd64 
org.label-schema.build-date: Friday_6_December_2024_14:25:47_CET  
org.label-schema.schema-version: 1.0      
org.label-schema.usage.singularity.deffile.bootstrap: docker   
org.label-schema.usage.singularity.deffile.from: nyudiffusionmri/designer2:main  
org.label-schema.usage.singularity.version: 4.1.1 
```

Command to run designer is:
`singularity run --nv --bind .:/mnt designer2_main.sif designer -denoise -shrinkage frob -adaptive_patch -rician -degibbs -pf 1 -eddy -rpe_pair ${pa} -normalize -mask -b1correct -scratch /mnt/processing -nocleanup ${dwi} ${dwi_out}`

Error:
```
... B1 correction...
Command:  dwibiascorrect ants -bias biasfield.mif working.mif dwibc.mif

designer: [ERROR] dwibiascorrect ants -bias biasfield.mif working.mif dwibc.mif (designer_func_wrappers.py:981)
designer: [ERROR] Information from failed command:
designer:
          dwibiascorrect:
          dwibiascorrect: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.
          dwibiascorrect:
          dwibiascorrect: Generated scratch directory: /mnt/processing/designer-tmp-7FS5E1/dwibiascorrect-tmp-28GBWG/
          Command:  mrconvert /mnt/processing/designer-tmp-7FS5E1/working.mif /mnt/processing/designer-tmp-7FS5E1/dwibiascorrect-tmp-28GBWG/in.mif
          dwibiascorrect: Changing to scratch directory (/mnt/processing/designer-tmp-7FS5E1/dwibiascorrect-tmp-28GBWG/)
          Command:  dwi2mask legacy in.mif mask.mif

          dwibiascorrect: [ERROR] Could not find ANTS program N4BiasFieldCorrection; please check installation
designer:
designer: [ERROR] For debugging, inspect contents of scratch directory: /mnt/processing/designer-tmp-7FS5E1/
designer: Scratch directory retained; location: /mnt/processing/designer-tmp-7FS5E1/
```

It looks like ANTs is not installed in the singularity (or docker) image. I don't know if this is the correct place to submit this issue, if not, please let me know where best to submit an issue with the docker container.

Thanks in advance!
