### ISSUE TITLE
Eddy fails because of double quotation marks in dwifslpreproc -eddy_options

### ISSUE THREAD

**Issue by pfuchs** [NYU-DiffusionMRI/DESIGNER-v2#23]
I get the following error when running the docker container (both the "main" and "v2.0.11" tags)

```
Command:  dwifslpreproc -nocleanup -scratch "eddy_processing_1" -eddy_options "" --cnr_maps --repol --data_is_shelled "" -rpe_none -eddy_mask "topup_corrected_1_brain_mask.nii.gz" -topup_files "topup_results_1" -pe_dir "j-" "dwi_pre_eddy_1.mif" "dwi_post_eddy_1.mif"
Command:  dwiextract -bzero "dwi_post_eddy_1.mif" - | mrmath - mean "b0_post_eddy_1.nii" -axis 3

designer: [ERROR] dwiextract -bzero "dwi_post_eddy_1.mif" - | mrmath - mean "b0_post_eddy_1.nii" -axis 3 (designer_func_wrappers.py:697)
designer: [ERROR] Information from failed command:
designer:
          dwiextract: [ERROR] failed to open key/value file "dwi_post_eddy_1.mif": No such file or directory
          dwiextract: [ERROR] error opening image "dwi_post_eddy_1.mif"
          mrmath: [ERROR] no filename supplied to standard input (broken pipe?)
          mrmath: [ERROR] error opening image "-"
```

the dwifslpreproc command runs fine without the double quotation marks as

```
dwifslpreproc -nocleanup -scratch "eddy_processing_1" -eddy_options " --cnr_maps --repol --data_is_shelled " -rpe_none -eddy_mask "topup_corrected_1_brain_mask.nii.gz" -topup_files "topup_results_1" -pe_dir "j-" "dwi_pre_eddy_1.mif" "dwi_post_eddy_1.mif"
```

which leads me to believe the dwiextract error is because of silent fail from dwifslpreproc (when run with the double quotation marks it returns the same result as running with -h or without inputs).
